### ISSUE TITLE
Support for Hibernate 5.x

### ISSUE THREAD

**Issue by YoussefArfaoui** [gert-wijns/TypeSafeQueryBuilder#69]
Hello Gert

Please when are planing to provide  support for Hibernate 5.x. is it in the near roadmap 

Respect
Youssef

**Comment by gert-wijns** [comment]
Hello, I've already implemented the support for the left joins (which use hibernate 5.1.0.Final)
I've upgraded the tsqb version to 2.0.0 and included this. I've also created a release so
I think it should be available sometimes tomorrow.

**Comment by YoussefArfaoui** [comment]
Thanks
Youssef
