### ISSUE TITLE
case when eq a String give an error

### ISSUE THREAD

**Issue by borisvereertbrugghen** [gert-wijns/TypeSafeQueryBuilder#92]
if (value instanceof TypeSafeValue<?>) {
            throw new IllegalArgumentException(String.format("The value [%s] is already a type safe value.", value));
        }
        @SuppressWarnings("unchecked")
        TypeSafeValue<VAL> selectedValue = (TypeSafeValue<VAL>) getRootQuery().dequeueSelectedValue();
        if (selectedValue != null) {
            return selectedValue;
        }
        List<TypeSafeQueryProxyData> invocations = dequeueInvocations();

The dequeue of the invocation should happen also when selectedValue  is actually a real value

TSQB 3.0.0

**Comment by gert-wijns** [comment]
The problem was actually that CaseTypeSafeValue was doing its own thing with invocation handling. Modified it to use the same logic as in the query instead here.
